# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html
from pathlib import Path
from typing import Any

from sphinx.application import Sphinx
from sphinx.ext import apidoc

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = "CDEK Python SDK v2"
copyright = "2025, Maksim Shurupov"  # noqa: A001
author = "Maksim Shurupov"
release = "1.1.6"

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "myst_parser",
    "sphinx.ext.napoleon",
    "sphinx.ext.autodoc",
    "sphinx.ext.viewcode",
]
napoleon_google_docstring = False

# The suffix of source filenames.
source_suffix = [
    ".rst",
    ".md",
]

# Language for content autogenerated by Sphinx
language = "ru"

# Add any paths that contain templates here, relative to this directory.
templates_path = [
    "_templates",
]

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
]


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "furo"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {
    "light_css_variables": {
        "color-brand-primary": "#0066cc",
        "color-brand-content": "#0066cc",
        "color-sidebar-background": "#f8f9fa",
        "color-sidebar-background-border": "#e1e4e8",
        "color-sidebar-caption-text": "#586069",
        "color-sidebar-link-text": "#24292e",
        "color-sidebar-link-text--top-level": "#24292e",
        "color-sidebar-search-background": "#ffffff",
        "color-sidebar-search-border": "#e1e4e8",
        "color-sidebar-search-text": "#24292e",
        "color-sidebar-search-placeholder-text": "#586069",
    },
    "dark_css_variables": {
        "color-brand-primary": "#4a9eff",
        "color-brand-content": "#4a9eff",
        "color-sidebar-background": "#1a1a1a",
        "color-sidebar-background-border": "#2d2d2d",
        "color-sidebar-caption-text": "#8b949e",
        "color-sidebar-link-text": "#c9d1d9",
        "color-sidebar-link-text--top-level": "#c9d1d9",
        "color-sidebar-search-background": "#161b22",
        "color-sidebar-search-border": "#30363d",
        "color-sidebar-search-text": "#c9d1d9",
        "color-sidebar-search-placeholder-text": "#8b949e",
    },
    "sidebar_hide_name": False,
    "navigation_with_keys": True,
    "top_of_page_button": "back-to-top",
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

# These paths are either relative to html_static_path
# or fully qualified paths (eg. https://...)
html_css_files = [
    "custom.css",
]


# -- Automatically run sphinx-apidoc -----------------------------------------


def run_apidoc(_: Any) -> None:
    """Run sphinx-apidoc."""
    docs_path = Path(__file__).parent
    module_path = docs_path.parent / "src" / "cdek"

    apidoc.main(
        [
            "--force",
            "--module-first",
            "-o",
            docs_path.as_posix(),
            module_path.as_posix(),
        ]
    )


def setup(app: Sphinx) -> None:
    """Setup sphinx."""
    app.connect("builder-inited", run_apidoc)
